// <auto-generated />
using System;
using ClanRatingTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClanRatingTracker.Migrations
{
    [DbContext(typeof(ClanTrackingContext))]
    [Migration("20250915153907_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("ClanRatingTracker.Models.ClanMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PersonalClanRating")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RecordedAt")
                        .HasDatabaseName("IX_ClanMembers_RecordedAt");

                    b.HasIndex("Username", "RecordedAt")
                        .HasDatabaseName("IX_ClanMembers_Username_RecordedAt");

                    b.ToTable("ClanMembers");
                });
#pragma warning restore 612, 618
        }
    }
}
