// <auto-generated />
using System;
using ClanRatingTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClanRatingTracker.Migrations
{
    [DbContext(typeof(ClanTrackingContext))]
    partial class ClanTrackingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("ClanRatingTracker.Models.ClanMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FirstSeen")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("IX_ClanMembers_Username");

                    b.ToTable("ClanMembers", (string)null);
                });

            modelBuilder.Entity("ClanRatingTracker.Models.ClanRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClanMemberId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PersonalClanRating")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RecordedAt")
                        .HasDatabaseName("IX_ClanRatings_RecordedAt");

                    b.HasIndex("ClanMemberId", "RecordedAt")
                        .HasDatabaseName("IX_ClanRatings_MemberId_RecordedAt");

                    b.ToTable("ClanRatings", (string)null);
                });

            modelBuilder.Entity("ClanRatingTracker.Models.ClanRating", b =>
                {
                    b.HasOne("ClanRatingTracker.Models.ClanMember", "ClanMember")
                        .WithMany("Ratings")
                        .HasForeignKey("ClanMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClanMember");
                });

            modelBuilder.Entity("ClanRatingTracker.Models.ClanMember", b =>
                {
                    b.Navigation("Ratings");
                });
#pragma warning restore 612, 618
        }
    }
}
